name: Android Signed build
on:
  workflow_dispatch:
jobs:
  Android-Signed:
    runs-on: ubuntu-latest
    steps:

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore/RN-TEST-APP-RELEASE-KEY.keystore'
          encodedString: ${{ secrets.ANDROID_SIGNINGKEYBASE64 }}

      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'gradle'
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build release AAB
        run: cd android && ./gradlew bundleRelease
        env:
          ANDROID_ALIAS: ${{ secrets.ANDROID_ALIAS }}
          ANDROID_KEYPASSWORD: ${{ secrets.ANDROID_KEYPASSWORD }}
          ANDROID_KEYSTOREPASSWORD: ${{ secrets.ANDROID_KEYSTOREPASSWORD }}
        
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: Signed App Bundle
          path: android/app/build/outputs/bundle/release/app-release.aab
