name: Android Debug build
on:
  workflow_dispatch:
jobs:
  Android-Debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'gradle'
        
      - name: Run debug build with Gradel Wrapper
        run: cd android && ./gradlew assembleDebug
        
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: Android Debug Bundle
          path: android/app/build/outputs/apk/debug/app-debug.apk
